### ISSUE TITLE
Is anybody actively working on this addon?

### ISSUE THREAD

**Issue by hjanjua** [humla/canadanepal-xbmc#26]
I saw a recent activity on this project... Is there anybody working on this or ?

**Comment by humla** [comment]
yes, this add-on is still being worked on.

We just fixed the add-on after the major redesign of the einthusan website.
The add-on is working now.

**Comment by YoColdRain** [comment]
Humla, I'm not sure if you realize but I've submitted pull request 4-5 days back, for a fix and new functionality.

**Comment by humla** [comment]
thanks ycoldrain..noticed it..but i have been out of my home for the last
week so, not able to package it up. will do it when I get home in 2 days.
sorry about it.

On 21 Mar 2017 7:06 pm, "YoColdRain" <notifications@github.com> wrote:

Humla, I'm not sure if you realize but I've submitted pull request 4-5 days
back, for a fix and new functionality.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/humla/canadanepal-xbmc/issues/26#issuecomment-288186089>,
or mute the thread
